/**
 * Velora ERP — Permission Constants
 * Every permission key used across the system is defined here.
 * Roles map to these keys in auth.service.js
 */

export const PERMISSIONS = {
  // Core
  COMPANY_READ: "company:view",
  COMPANY_UPDATE: "company:edit",
  COMPANY_DELETE: "company:delete",
  BRANCH_READ: "branches:view",
  BRANCH_CREATE: "branches:create",
  BRANCH_UPDATE: "branches:edit",
  BRANCH_DELETE: "branches:delete",
  USER_READ: "users:view",
  USER_CREATE: "users:create",
  USER_UPDATE: "users:edit",
  USER_DELETE: "users:delete",
  AUDIT_READ: "audit:view",

  // Products / Master
  PRODUCT_READ: "products:view",
  PRODUCT_CREATE: "products:create",
  PRODUCT_UPDATE: "products:edit",
  PRODUCT_DELETE: "products:delete",
  MASTER_READ: "master:view",
  MASTER_CREATE: "master:create",
  MASTER_UPDATE: "master:edit",
  MASTER_DELETE: "master:delete",

  // Sales
  SALES_READ: "sales:view",
  SALES_CREATE: "sales:create",
  SALES_UPDATE: "sales:edit",
  SALES_DELETE: "sales:delete",
  SALES_APPROVE: "sales:approve",
  SALES_PAYMENT: "sales:payment",

  // Purchase
  PURCHASE_READ: "purchase:view",
  PURCHASE_CREATE: "purchase:create",
  PURCHASE_UPDATE: "purchase:edit",
  PURCHASE_DELETE: "purchase:delete",
  PURCHASE_APPROVE: "purchase:approve",
  PURCHASE_PAYMENT: "purchase:payment",

  // Inventory
  INVENTORY_READ: "inventory:view",
  INVENTORY_CREATE: "inventory:create",
  INVENTORY_UPDATE: "inventory:edit",
  INVENTORY_ADJUST: "inventory:adjust",
  INVENTORY_TRANSFER: "inventory:transfer",

  // Accounts
  ACCOUNTS_READ: "accounts:view",
  ACCOUNTS_CREATE: "accounts:create",
  ACCOUNTS_UPDATE: "accounts:edit",
  ACCOUNTS_JOURNAL: "accounts:journal",
  ACCOUNTS_REPORT: "accounts:report",

  // Manufacturing
  MFG_READ: "manufacturing:view",
  MFG_CREATE: "manufacturing:create",
  MFG_UPDATE: "manufacturing:edit",
  MFG_APPROVE: "manufacturing:approve",
  MFG_QUALITY: "manufacturing:quality",

  // CRM
  CRM_READ: "crm:view",
  CRM_CREATE: "crm:create",
  CRM_UPDATE: "crm:edit",
  CRM_DELETE: "crm:delete",
  CRM_CONVERT: "crm:convert",

  // HR
  HR_READ: "hr:view",
  HR_CREATE: "hr:create",
  HR_UPDATE: "hr:edit",

  // Reports
  REPORTS_READ: "reports:view",
  REPORTS_EXPORT: "reports:export",

  // Settings
  SETTINGS_READ: "settings:view",
  SETTINGS_MANAGE: "settings:manage",

  // Admin
  ADMIN_VIEW: "admin:view",
  ADMIN_MANAGE_ROLES: "admin:manageRoles",
  ADMIN_MANAGE_USERS: "admin:manageUsers",
  ADMIN_MANAGE_PERMISSIONS: "admin:managePermissions",

  // Dashboard
  DASHBOARD_READ: "dashboard:view",
};

/**
 * Role -> permission mapping.
 * OWNER has wildcard "*" which bypasses all permission checks.
 */
export const ROLE_PERMISSIONS = {
  OWNER: ["*"],
  FOUNDER: ["*"],
  SUPER_ADMIN: ["*"],

  ADMIN: [
    PERMISSIONS.COMPANY_READ, PERMISSIONS.COMPANY_UPDATE,
    PERMISSIONS.BRANCH_READ, PERMISSIONS.BRANCH_CREATE, PERMISSIONS.BRANCH_UPDATE, PERMISSIONS.BRANCH_DELETE,
    PERMISSIONS.USER_READ, PERMISSIONS.USER_CREATE, PERMISSIONS.USER_UPDATE, PERMISSIONS.USER_DELETE,
    PERMISSIONS.PRODUCT_READ, PERMISSIONS.PRODUCT_CREATE, PERMISSIONS.PRODUCT_UPDATE, PERMISSIONS.PRODUCT_DELETE,
    PERMISSIONS.MASTER_READ, PERMISSIONS.MASTER_CREATE, PERMISSIONS.MASTER_UPDATE, PERMISSIONS.MASTER_DELETE,
    PERMISSIONS.SALES_READ, PERMISSIONS.SALES_CREATE, PERMISSIONS.SALES_UPDATE, PERMISSIONS.SALES_DELETE, PERMISSIONS.SALES_APPROVE, PERMISSIONS.SALES_PAYMENT,
    PERMISSIONS.PURCHASE_READ, PERMISSIONS.PURCHASE_CREATE, PERMISSIONS.PURCHASE_UPDATE, PERMISSIONS.PURCHASE_DELETE, PERMISSIONS.PURCHASE_APPROVE, PERMISSIONS.PURCHASE_PAYMENT,
    PERMISSIONS.INVENTORY_READ, PERMISSIONS.INVENTORY_CREATE, PERMISSIONS.INVENTORY_UPDATE, PERMISSIONS.INVENTORY_ADJUST, PERMISSIONS.INVENTORY_TRANSFER,
    PERMISSIONS.ACCOUNTS_READ, PERMISSIONS.ACCOUNTS_CREATE, PERMISSIONS.ACCOUNTS_UPDATE, PERMISSIONS.ACCOUNTS_JOURNAL, PERMISSIONS.ACCOUNTS_REPORT,
    PERMISSIONS.MFG_READ, PERMISSIONS.MFG_CREATE, PERMISSIONS.MFG_UPDATE, PERMISSIONS.MFG_APPROVE, PERMISSIONS.MFG_QUALITY,
    PERMISSIONS.CRM_READ, PERMISSIONS.CRM_CREATE, PERMISSIONS.CRM_UPDATE, PERMISSIONS.CRM_DELETE, PERMISSIONS.CRM_CONVERT,
    PERMISSIONS.HR_READ, PERMISSIONS.HR_CREATE, PERMISSIONS.HR_UPDATE,
    PERMISSIONS.REPORTS_READ, PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.SETTINGS_READ, PERMISSIONS.SETTINGS_MANAGE,
    PERMISSIONS.ADMIN_VIEW, PERMISSIONS.ADMIN_MANAGE_ROLES, PERMISSIONS.ADMIN_MANAGE_USERS, PERMISSIONS.ADMIN_MANAGE_PERMISSIONS,
    PERMISSIONS.DASHBOARD_READ, PERMISSIONS.AUDIT_READ,
  ],

  SALES_MANAGER: [
    PERMISSIONS.COMPANY_READ, PERMISSIONS.BRANCH_READ, PERMISSIONS.PRODUCT_READ, PERMISSIONS.MASTER_READ,
    PERMISSIONS.SALES_READ, PERMISSIONS.SALES_CREATE, PERMISSIONS.SALES_UPDATE, PERMISSIONS.SALES_APPROVE, PERMISSIONS.SALES_PAYMENT,
    PERMISSIONS.CRM_READ, PERMISSIONS.CRM_CREATE, PERMISSIONS.CRM_UPDATE, PERMISSIONS.CRM_CONVERT,
    PERMISSIONS.INVENTORY_READ, PERMISSIONS.DASHBOARD_READ, PERMISSIONS.REPORTS_READ, PERMISSIONS.AUDIT_READ,
  ],

  SALES_EXECUTIVE: [
    PERMISSIONS.COMPANY_READ, PERMISSIONS.BRANCH_READ, PERMISSIONS.PRODUCT_READ, PERMISSIONS.MASTER_READ,
    PERMISSIONS.SALES_READ, PERMISSIONS.SALES_CREATE, PERMISSIONS.SALES_UPDATE,
    PERMISSIONS.CRM_READ, PERMISSIONS.CRM_CREATE, PERMISSIONS.CRM_UPDATE,
    PERMISSIONS.INVENTORY_READ, PERMISSIONS.DASHBOARD_READ,
  ],

  INVENTORY_MANAGER: [
    PERMISSIONS.COMPANY_READ, PERMISSIONS.BRANCH_READ, PERMISSIONS.PRODUCT_READ, PERMISSIONS.PRODUCT_CREATE, PERMISSIONS.PRODUCT_UPDATE,
    PERMISSIONS.MASTER_READ, PERMISSIONS.MASTER_CREATE, PERMISSIONS.MASTER_UPDATE,
    PERMISSIONS.INVENTORY_READ, PERMISSIONS.INVENTORY_CREATE, PERMISSIONS.INVENTORY_UPDATE, PERMISSIONS.INVENTORY_ADJUST, PERMISSIONS.INVENTORY_TRANSFER,
    PERMISSIONS.PURCHASE_READ, PERMISSIONS.DASHBOARD_READ, PERMISSIONS.REPORTS_READ, PERMISSIONS.AUDIT_READ,
  ],

  STORE_KEEPER: [
    PERMISSIONS.COMPANY_READ, PERMISSIONS.BRANCH_READ, PERMISSIONS.PRODUCT_READ, PERMISSIONS.PRODUCT_CREATE, PERMISSIONS.PRODUCT_UPDATE,
    PERMISSIONS.MASTER_READ, PERMISSIONS.MASTER_CREATE,
    PERMISSIONS.INVENTORY_READ, PERMISSIONS.INVENTORY_CREATE, PERMISSIONS.INVENTORY_UPDATE, PERMISSIONS.INVENTORY_ADJUST, PERMISSIONS.INVENTORY_TRANSFER,
    PERMISSIONS.PURCHASE_READ, PERMISSIONS.DASHBOARD_READ, PERMISSIONS.AUDIT_READ,
  ],

  PROCUREMENT_MANAGER: [
    PERMISSIONS.COMPANY_READ, PERMISSIONS.BRANCH_READ, PERMISSIONS.PRODUCT_READ, PERMISSIONS.MASTER_READ,
    PERMISSIONS.PURCHASE_READ, PERMISSIONS.PURCHASE_CREATE, PERMISSIONS.PURCHASE_UPDATE, PERMISSIONS.PURCHASE_APPROVE, PERMISSIONS.PURCHASE_PAYMENT,
    PERMISSIONS.INVENTORY_READ, PERMISSIONS.DASHBOARD_READ, PERMISSIONS.REPORTS_READ, PERMISSIONS.AUDIT_READ,
  ],

  FINANCE_MANAGER: [
    PERMISSIONS.COMPANY_READ, PERMISSIONS.BRANCH_READ, PERMISSIONS.PRODUCT_READ, PERMISSIONS.MASTER_READ,
    PERMISSIONS.SALES_READ, PERMISSIONS.PURCHASE_READ,
    PERMISSIONS.ACCOUNTS_READ, PERMISSIONS.ACCOUNTS_CREATE, PERMISSIONS.ACCOUNTS_UPDATE, PERMISSIONS.ACCOUNTS_JOURNAL, PERMISSIONS.ACCOUNTS_REPORT,
    PERMISSIONS.INVENTORY_READ, PERMISSIONS.DASHBOARD_READ, PERMISSIONS.REPORTS_READ, PERMISSIONS.REPORTS_EXPORT, PERMISSIONS.AUDIT_READ,
  ],

  ACCOUNTANT: [
    PERMISSIONS.COMPANY_READ, PERMISSIONS.BRANCH_READ, PERMISSIONS.PRODUCT_READ, PERMISSIONS.MASTER_READ,
    PERMISSIONS.SALES_READ, PERMISSIONS.PURCHASE_READ,
    PERMISSIONS.ACCOUNTS_READ, PERMISSIONS.ACCOUNTS_CREATE, PERMISSIONS.ACCOUNTS_UPDATE, PERMISSIONS.ACCOUNTS_JOURNAL, PERMISSIONS.ACCOUNTS_REPORT,
    PERMISSIONS.INVENTORY_READ, PERMISSIONS.DASHBOARD_READ, PERMISSIONS.AUDIT_READ,
  ],

  MANUFACTURING_MANAGER: [
    PERMISSIONS.COMPANY_READ, PERMISSIONS.BRANCH_READ, PERMISSIONS.PRODUCT_READ, PERMISSIONS.MASTER_READ,
    PERMISSIONS.MFG_READ, PERMISSIONS.MFG_CREATE, PERMISSIONS.MFG_UPDATE, PERMISSIONS.MFG_APPROVE, PERMISSIONS.MFG_QUALITY,
    PERMISSIONS.INVENTORY_READ, PERMISSIONS.DASHBOARD_READ, PERMISSIONS.REPORTS_READ, PERMISSIONS.AUDIT_READ,
  ],

  HR_MANAGER: [
    PERMISSIONS.COMPANY_READ, PERMISSIONS.BRANCH_READ,
    PERMISSIONS.USER_READ, PERMISSIONS.USER_CREATE, PERMISSIONS.USER_UPDATE,
    PERMISSIONS.HR_READ, PERMISSIONS.HR_CREATE, PERMISSIONS.HR_UPDATE,
    PERMISSIONS.AUDIT_READ, PERMISSIONS.DASHBOARD_READ,
  ],

  CRM_MANAGER: [
    PERMISSIONS.COMPANY_READ, PERMISSIONS.BRANCH_READ, PERMISSIONS.PRODUCT_READ, PERMISSIONS.MASTER_READ,
    PERMISSIONS.CRM_READ, PERMISSIONS.CRM_CREATE, PERMISSIONS.CRM_UPDATE, PERMISSIONS.CRM_DELETE, PERMISSIONS.CRM_CONVERT,
    PERMISSIONS.SALES_READ, PERMISSIONS.DASHBOARD_READ, PERMISSIONS.REPORTS_READ, PERMISSIONS.AUDIT_READ,
  ],

  VIEWER: [
    PERMISSIONS.COMPANY_READ, PERMISSIONS.BRANCH_READ, PERMISSIONS.PRODUCT_READ, PERMISSIONS.MASTER_READ,
    PERMISSIONS.SALES_READ, PERMISSIONS.PURCHASE_READ, PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.ACCOUNTS_READ, PERMISSIONS.MFG_READ, PERMISSIONS.CRM_READ,
    PERMISSIONS.HR_READ, PERMISSIONS.DASHBOARD_READ, PERMISSIONS.REPORTS_READ,
  ],

  // Legacy names for backward compat
  SALESMAN: [
    PERMISSIONS.COMPANY_READ, PERMISSIONS.BRANCH_READ, PERMISSIONS.PRODUCT_READ, PERMISSIONS.MASTER_READ,
    PERMISSIONS.SALES_READ, PERMISSIONS.SALES_CREATE, PERMISSIONS.SALES_UPDATE,
    PERMISSIONS.INVENTORY_READ, PERMISSIONS.DASHBOARD_READ,
  ],
  PURCHASE_MANAGER: [
    PERMISSIONS.COMPANY_READ, PERMISSIONS.BRANCH_READ, PERMISSIONS.PRODUCT_READ, PERMISSIONS.MASTER_READ,
    PERMISSIONS.PURCHASE_READ, PERMISSIONS.PURCHASE_CREATE, PERMISSIONS.PURCHASE_UPDATE, PERMISSIONS.PURCHASE_APPROVE, PERMISSIONS.PURCHASE_PAYMENT,
    PERMISSIONS.INVENTORY_READ, PERMISSIONS.DASHBOARD_READ, PERMISSIONS.AUDIT_READ,
  ],
  PRODUCTION_OPERATOR: [
    PERMISSIONS.COMPANY_READ, PERMISSIONS.BRANCH_READ, PERMISSIONS.PRODUCT_READ, PERMISSIONS.MASTER_READ,
    PERMISSIONS.MFG_READ, PERMISSIONS.MFG_CREATE, PERMISSIONS.MFG_UPDATE, PERMISSIONS.MFG_QUALITY,
    PERMISSIONS.INVENTORY_READ, PERMISSIONS.DASHBOARD_READ,
  ],
};
